### ISSUE TITLE
[1.10.2]与Pixelmon冲突

### ISSUE THREAD

**Issue by jiastku98** [SkyStardust/InputMethodBlocker#3]
与pixelmon同时安装，按E打开物品栏，移动鼠标，闪退。
log：
Description: Updating screen events

java.lang.RuntimeException: java.lang.NoSuchFieldException: field_147062_A
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:191)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:516)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldException: field_147062_A
	at java.lang.Class.getDeclaredField(Unknown Source)
	at com.github.skystardust.InputMethodBlocker.ReflectionUtils.getPrivateField(ReflectionUtils.java:9)
	at com.github.skystardust.InputMethodBlocker.GameEventHandle.onCreativeGUI(GameEventHandle.java:50)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_138_GameEventHandle_onCreativeGUI_MouseInputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:191)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:516)

-- Affected screen --
Details:
	Screen name: com.pixelmonmod.pixelmon.client.gui.inventory.GuiCreativeInventoryExtended

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Haku98'/32, l='MpServer', x=-478.91, y=71.50, z=-750.47]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (457,4,-36), Chunk: (at 9,0,12 in 28,-3; contains blocks 448,0,-48 to 463,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 21764 game time, 21764 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 113 total; [EntityPixelmon['班基拉斯'/10242, l='MpServer', x=-473.46, y=52.00, z=-692.07], EntityZombie['entity.Zombie.name'/10756, l='MpServer', x=-523.50, y=96.00, z=-715.50], EntitySpider['蜘蛛'/7175, l='MpServer', x=-494.56, y=50.00, z=-811.18], EntityPixelmon['烛光灵'/8967, l='MpServer', x=-523.75, y=73.00, z=-759.49], EntitySpider['蜘蛛'/7176, l='MpServer', x=-492.50, y=50.00, z=-813.50], EntitySpider['蜘蛛'/7177, l='MpServer', x=-497.09, y=50.00, z=-812.09], EntityBat['蝙蝠'/4108, l='MpServer', x=-449.35, y=50.09, z=-765.03], EntityCreeper['爬行者'/10765, l='MpServer', x=-530.50, y=50.00, z=-704.50], EntityCreeper['爬行者'/7443, l='MpServer', x=-477.50, y=52.00, z=-678.50], EntityCreeper['爬行者'/7444, l='MpServer', x=-482.50, y=52.00, z=-676.50], EntityBat['蝙蝠'/7706, l='MpServer', x=-470.33, y=54.05, z=-707.18], EntityBat['蝙蝠'/7708, l='MpServer', x=-438.98, y=55.04, z=-679.72], EntityPixelmon['催眠貘'/6943, l='MpServer', x=-464.32, y=96.00, z=-711.60], EntitySpider['蜘蛛'/33, l='MpServer', x=-518.99, y=50.00, z=-774.00], GCEntityClientPlayerMP['Haku98'/32, l='MpServer', x=-478.91, y=71.50, z=-750.47], EntityPixelmon['尾立'/12579, l='MpServer', x=-453.50, y=50.00, z=-703.72], EntityBat['蝙蝠'/7716, l='MpServer', x=-484.79, y=51.92, z=-725.64], EntityPixelmon['飘飘球'/12332, l='MpServer', x=-452.50, y=50.00, z=-824.50], EntitySpider['蜘蛛'/3120, l='MpServer', x=-504.50, y=52.00, z=-684.50], EntityBat['蝙蝠'/4928, l='MpServer', x=-497.44, y=55.40, z=-706.63], EntityCreeper['爬行者'/65, l='MpServer', x=-512.85, y=50.00, z=-813.15], EntitySkeleton['骷髅'/6210, l='MpServer', x=-461.50, y=52.00, z=-691.50], EntityBat['蝙蝠'/4931, l='MpServer', x=-541.13, y=51.02, z=-707.95], EntitySkeleton['骷髅'/6211, l='MpServer', x=-501.21, y=50.00, z=-735.58], EntitySkeleton['骷髅'/6212, l='MpServer', x=-484.79, y=50.00, z=-740.25], EntityBat['蝙蝠'/4932, l='MpServer', x=-480.25, y=61.10, z=-739.86], EntityPixelmon['尾立'/12105, l='MpServer', x=-521.63, y=50.00, z=-791.05], EntityCreeper['爬行者'/77, l='MpServer', x=-504.57, y=64.00, z=-792.22], EntitySkeleton['骷髅'/11088, l='MpServer', x=-414.54, y=52.00, z=-793.67], EntitySpider['蜘蛛'/6226, l='MpServer', x=-511.50, y=52.00, z=-696.50], EntityZombie['僵尸'/7507, l='MpServer', x=-532.45, y=50.00, z=-721.42], EntityPixelmon['飘飘球'/3415, l='MpServer', x=-456.68, y=106.00, z=-803.50], EntityCreeper['爬行者'/7511, l='MpServer', x=-531.50, y=50.00, z=-715.50], EntityPixelmon['小拉达'/12631, l='MpServer', x=-541.50, y=52.00, z=-847.50], EntityPixelmon['小拉达'/12632, l='MpServer', x=-540.50, y=52.00, z=-846.50], EntityZombie['僵尸'/89, l='MpServer', x=-510.71, y=50.00, z=-804.19], NPCTrainer['4'/12122, l='MpServer', x=-470.50, y=52.00, z=-672.50], EntitySkeleton['骷髅'/91, l='MpServer', x=-531.26, y=50.00, z=-770.66], EntityBat['蝙蝠'/6747, l='MpServer', x=-492.51, y=53.82, z=-790.84], EntityBat['蝙蝠'/6748, l='MpServer', x=-479.57, y=50.05, z=-781.97], EntityBat['蝙蝠'/6749, l='MpServer', x=-471.20, y=56.32, z=-769.68], EntityZombie['僵尸'/11101, l='MpServer', x=-406.77, y=52.00, z=-790.50], EntityBat['蝙蝠'/6751, l='MpServer', x=-481.14, y=55.99, z=-813.62], EntityBat['蝙蝠'/11872, l='MpServer', x=-490.77, y=50.57, z=-797.24], EntityBat['蝙蝠'/11874, l='MpServer', x=-496.20, y=55.84, z=-814.36], EntityZombie['僵尸'/102, l='MpServer', x=-480.65, y=50.00, z=-788.24], EntitySpider['蜘蛛'/103, l='MpServer', x=-478.81, y=50.00, z=-763.61], EntitySpider['蜘蛛'/106, l='MpServer', x=-513.96, y=50.00, z=-771.98], EntityWitch['女巫'/107, l='MpServer', x=-507.44, y=50.00, z=-780.29], EntityZombie['僵尸'/7793, l='MpServer', x=-476.72, y=50.00, z=-785.53], EntityCreeper['爬行者'/11121, l='MpServer', x=-534.81, y=98.00, z=-732.53], EntityZombie['僵尸'/7794, l='MpServer', x=-473.64, y=50.00, z=-795.25], EntityZombie['僵尸'/11122, l='MpServer', x=-533.50, y=50.00, z=-728.50], EntityZombie['僵尸'/11123, l='MpServer', x=-530.50, y=50.00, z=-729.50], EntitySpider['蜘蛛'/11125, l='MpServer', x=-541.50, y=50.00, z=-729.50], EntitySpider['蜘蛛'/11126, l='MpServer', x=-553.01, y=50.00, z=-732.00], EntityPixelmon['猫鼬少'/12410, l='MpServer', x=-492.50, y=50.00, z=-785.50], EntityCreeper['爬行者'/7803, l='MpServer', x=-475.84, y=50.00, z=-754.70], EntityPixelmon['魅力喵'/10620, l='MpServer', x=-388.50, y=52.00, z=-822.50], EntityZombie['僵尸'/8580, l='MpServer', x=-494.59, y=50.00, z=-810.15], EntityPixelmon['喵喵'/12676, l='MpServer', x=-385.50, y=52.00, z=-808.50], EntityPixelmon['魅力喵'/11911, l='MpServer', x=-446.50, y=100.50, z=-777.50], EntitySkeleton['骷髅'/8585, l='MpServer', x=-492.50, y=50.00, z=-795.50], EntityZombie['僵尸'/8590, l='MpServer', x=-439.50, y=50.00, z=-756.50], EntityPixelmon['盖盖虫'/7567, l='MpServer', x=-462.53, y=50.00, z=-698.59], EntitySkeleton['骷髅'/8591, l='MpServer', x=-440.50, y=50.00, z=-763.50], EntityCreeper['爬行者'/2959, l='MpServer', x=-539.50, y=52.00, z=-686.50], EntityPixelmon['小拉达'/2711, l='MpServer', x=-459.15, y=74.00, z=-765.71], EntityPixelmon['喵喵'/10647, l='MpServer', x=-415.50, y=52.00, z=-823.50], EntityPixelmon['小拉达'/2712, l='MpServer', x=-459.50, y=74.00, z=-766.10], EntityPixelmon['喵喵'/10648, l='MpServer', x=-418.50, y=52.00, z=-822.50], EntityPixelmon['尾立'/10156, l='MpServer', x=-431.27, y=50.00, z=-812.09], EntityPixelmon['催眠貘'/12460, l='MpServer', x=-468.89, y=52.47, z=-681.80], EntityPixelmon['向尾喵'/173, l='MpServer', x=-468.41, y=50.00, z=-774.57], NPCTrainer['5'/10157, l='MpServer', x=-424.54, y=52.00, z=-817.92], EntityPixelmon['催眠貘'/12461, l='MpServer', x=-467.39, y=52.53, z=-682.76], NPCTrainer['2'/12463, l='MpServer', x=-472.50, y=52.00, z=-683.50], EntityZombie['僵尸'/9658, l='MpServer', x=-523.36, y=50.00, z=-775.66], EntityZombie['僵尸'/9659, l='MpServer', x=-532.20, y=50.00, z=-782.23], EntitySpider['蜘蛛'/9662, l='MpServer', x=-527.94, y=50.00, z=-787.92], EntitySkeleton['骷髅'/5312, l='MpServer', x=-469.74, y=50.00, z=-727.47], EntitySkeleton['骷髅'/5313, l='MpServer', x=-466.30, y=50.00, z=-721.73], EntitySkeleton['骷髅'/5314, l='MpServer', x=-463.44, y=50.00, z=-721.78], NPCTrainer['2'/12227, l='MpServer', x=-484.50, y=52.00, z=-676.50], EntityBat['蝙蝠'/10951, l='MpServer', x=-487.36, y=50.03, z=-745.34], EntityBat['蝙蝠'/10952, l='MpServer', x=-478.46, y=51.40, z=-731.32], EntityBat['蝙蝠'/10953, l='MpServer', x=-479.48, y=56.94, z=-766.48], EntityPixelmon['胖丁'/7889, l='MpServer', x=-538.50, y=50.00, z=-701.50], EntityPixelmon['小拉达'/9937, l='MpServer', x=-408.50, y=52.00, z=-825.50], EntityPixelmon['小拉达'/9938, l='MpServer', x=-410.41, y=52.95, z=-825.59], NPCTrainer['1'/11218, l='MpServer', x=-439.16, y=52.00, z=-843.55], EntityPixelmon['烛光灵'/7892, l='MpServer', x=-499.22, y=50.00, z=-724.09], EntityZombie['僵尸'/11988, l='MpServer', x=-493.50, y=50.00, z=-757.50], EntityZombie['僵尸'/11990, l='MpServer', x=-503.24, y=50.00, z=-764.47], EntityPixelmon['随风球'/9178, l='MpServer', x=-508.50, y=50.00, z=-746.50], EntitySkeleton['骷髅'/11995, l='MpServer', x=-491.50, y=50.00, z=-758.50], EntitySkeleton['骷髅'/11996, l='MpServer', x=-494.50, y=50.00, z=-757.50], EntityZombie['僵尸'/11999, l='MpServer', x=-481.50, y=50.00, z=-702.50], EntityCreeper['爬行者'/12001, l='MpServer', x=-480.50, y=50.00, z=-703.50], EntitySkeleton['骷髅'/3814, l='MpServer', x=-419.50, y=52.00, z=-739.50], EntityCreeper['爬行者'/11239, l='MpServer', x=-540.50, y=50.00, z=-718.50], EntityCreeper['爬行者'/11240, l='MpServer', x=-542.50, y=50.00, z=-721.50], EntityCreeper['爬行者'/3818, l='MpServer', x=-522.20, y=50.00, z=-743.45], EntityCreeper['爬行者'/11243, l='MpServer', x=-538.50, y=50.00, z=-719.50], EntityCreeper['爬行者'/3820, l='MpServer', x=-517.83, y=50.00, z=-720.72], EntityCreeper['爬行者'/11244, l='MpServer', x=-536.50, y=50.00, z=-721.50], EntityZombie['僵尸'/12530, l='MpServer', x=-403.28, y=52.00, z=-731.80], EntityPixelmon['尾立'/5876, l='MpServer', x=-427.09, y=50.00, z=-778.51], EntityPixelmon['向尾喵'/4598, l='MpServer', x=-489.52, y=50.00, z=-777.60], EntityPixelmon['向尾喵'/4600, l='MpServer', x=-460.18, y=50.00, z=-790.79], EntityPixelmon['猫老大'/11513, l='MpServer', x=-576.50, y=52.00, z=-764.50], NPCTrainer['5'/11514, l='MpServer', x=-575.50, y=52.00, z=-767.50], EntityPixelmon['魅力喵'/5117, l='MpServer', x=-452.52, y=100.50, z=-789.48]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

多次测试，应该暂时和其他mod无关

**Comment by SkyStardust** [comment]
这个大概是因为神奇宝贝mod用asm修改了字段名，稍后会做支持,另外请提供一下你的游戏版本和神奇宝贝Mod版本

**Comment by jiastku98** [comment]
游戏1.10.2，pixelmon 5.1.2，pixelmon dark的2.4
